### ISSUE TITLE
How about adding ffmpeg in docker image?

### ISSUE THREAD

**Issue by n3ksus** [tiangolo/nginx-rtmp-docker#17]
with ffmpeg in it is useful to run exec directive.

**Comment by kevmo314** [comment]
@n3ksus I've created a [Dockerfile that compiles in ffmpeg here](https://gist.github.com/kevmo314/f73984bcd7247f59e2cd42b182d8fa77). Since various options are specified at compile-time, I've chosen to not publish it on dockerhub but you can customize the Dockerfile to your own needs.

**Comment by tiangolo** [comment]
I'm not currently using this Docker image so I wouldn't be able to work on it and test it. But maybe @kevmo314 solution can work for you @n3ksus . 🤓 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
