### ISSUE TITLE
Question: RTMP / RTSP

### ISSUE THREAD

**Issue by Plnda** [tiangolo/nginx-rtmp-docker#21]
Currently im trying to push a rtmp stream (GoPro) and output a rtsp stream so i can use that with my surveillance station (Synology) is that easy to add to this docker package?

**Comment by tiangolo** [comment]
I wouldn't know, I'm sorry. But you can try to create your own Docker image based on this one. 🤓 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
