### ISSUE TITLE
Install ffmpeg vaapi?

### ISSUE THREAD

**Issue by SvensenDE** [tiangolo/nginx-rtmp-docker#22]
Hi there

I have a question about "ffmpeg vaapi"

how can I install the Docker Container?

I'm quite new to Linux and docker containers

I would like to stream from my Synology 718+ with Intel Celeron J3455 to Twitch in 720p and 30 FPS

and if I have already read my way through correctly you need the coding "ffmpeg vaapi" because of the performance

I have nginx.conf here

would that be right?

`worker_processes auto;
rtmp_auto_push on;
events {}
rtmp {
    server {
        listen 1935;
        listen [::]:1935 ipv6only=on;    

        application live {
            live on;
            record off;
			exec ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -i rtmp://127.0.0.1/live -vcodec h264_vaapi -preset medium -x264opts nal-hrd=cbr:force-cfr=1:keyint=60 -r 30 -b:v 6000k -maxrate 6000k -bufsize 6000k -threads 12 -s hd720 -sws_flags spline -acodec copy -f flv rtmp://127.0.0.1/streamout;
        }

        application streamout {
           live on;
           record off;
           push rtmp://live-ber.twitch.tv/app/API;
        }

    }
}
`

sorry for my bad English

many greetings from Germany

Sven

**Comment by tiangolo** [comment]
Hey there! Sorry, I wouldn't really know, and I'm currently not using this Docker image myself, so there's not much I can help you with in this case. 😔 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
