### ISSUE TITLE
RTMPS support

### ISSUE THREAD

**Issue by peterhavener** [tiangolo/nginx-rtmp-docker#7]
Facebook has depricated RTMP and is forcing RTMPS now. Would it be possible to add support for RTMPS?

**Comment by tiangolo** [comment]
I think you should be able to create a custom `Dockerfile` and install `stunnel4` in it. And then follow a guide like this one, that uses the same nginx-rtmp plugin: https://dev.to/lax/rtmps-relay-with-stunnel-12d3
