### ISSUE TITLE
limit the diffusion via the stream keys

### ISSUE THREAD

**Issue by fabb24** [tiangolo/nginx-rtmp-docker#8]
Hello, 
Thank you for this work! It works perfectly and I love it.

However, is it possible to allow broadcasting only at certain stream keys to prevent anyone from broadcasting on the server?

If so, how can this be achieved?
thank you

**Comment by tiangolo** [comment]
Thanks for your patience.

I don't think that's possible directly with the rtmp module, you can check more on the official site: https://github.com/arut/nginx-rtmp-module

The way I would solve it would be to add a layer on top that lets some streams coming in but not others, I'm not really sure what would be the correct technological stack to do it though.

**Comment by valerio-bozzolan** [comment]
I think this should be re-opened, since it's a killer feature.
